name: threeJS_Viewer
version: 0.0.1+2

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  webview_flutter: ^3.0.2
  local_assets_server: ^2.0.2+12
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - web/
